version: '3.1'

services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - '35432:5432'
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - $POSTGRES_ADMINER_PORT:$POSTGRES_ADMINER_PORT

  app-api:
    build:
      context: ./app-api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:example@postgres:5432/todo-db
      NODE_ENV: development
      PORT: $PORT
    ports:
      - $PORT:$PORT
    command: npm run server:watch
    volumes:
      - .:/app/
      - /app/node_modules
